---
- hosts: 127.0.0.1
  connection: local
  remote_user: malk
  sudo: yes
  vars:
    http_port: 80
    max_clients: 200
  roles:
    - oracle-java-8
  tasks:
    - name: Upgrade the system
      apt: upgrade=dist update_cache=yes
    - name: Install StumpWM
      apt: name={{item}} state=latest
      with_items:
        - sbcl
        - cl-clx-sbcl
        - cl-ppcre
        - stumpwm
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
