---
- hosts: 127.0.0.1
  connection: local
  remote_user: malk
  sudo: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
    - name: Upgrade the system
      apt: upgrade=dist update_cache=yes
    - name: Install Cowsay
      apt: name=cowsay state=latest
    - name: Add Oracle Jave Repository
      apt_repository: repo='ppa:webupd8team/java'
    - name: Accept Java Licence
      shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    - name: Install Oracle Java
      apt: name=oracle-java8-installer state=latest
    - name: Set Java Env Variables
      apt: name=oracle-java8-set-default state=latest
    - name: Install StumpWM
      apt: name={{item}} state=latest
      with_items:
        - sbcl
        - cl-clx-sbcl
        - cl-ppcre
        - stumpwm
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
