---
- hosts: 127.0.0.1
  connection: local
#  remote_user: malk
#  sudo: yes
#  ask_pass: True
#  ask_sudo_pass: True
  vars:
    http_port: 80
    max_clients: 200
  tasks:
    - name: Upgrade the system
      apt: upgrade=dist update_cache=yes
    - name: Install Oracle Java
      apt_repository: repo='ppa:webupd8team/java'
      apt: name=oracle-java8-installer state=latest
    - name: Install StumpWM
      apt: name={{item}} state=latest
      with_items:
        - sbcl
        - cl-clx-sbcl
        - cl-ppcre
        - stumpwm
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
