---
- hosts: 127.0.0.1
  connection: local
  remote_user: malk
  sudo: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
    - name: Upgrade the system
      apt: upgrade=dist update_cache=yes
    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java'
    - name: Accept Java 8 Licence
      shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
      args:
        creates: /etc/oracle-java-8-licence-acceptance
    - name: Install Oracle Java 8
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - oracle-java8-set-default
    - name: Install StumpWM
      apt: name={{item}} state=latest
      with_items:
        - sbcl
        - cl-clx-sbcl
        - cl-ppcre
        - stumpwm
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
