---
- hosts: 127.0.0.1
  connection: local
  remote_user: malk
  sudo: yes
  roles:
    - dist-upgrade
    - oracle-java-8
  tasks:
    - name: Install StumpWM
      apt: name={{item}} state=latest
      with_items:
        - sbcl
        - cl-clx-sbcl
        - cl-ppcre
        - stumpwm
