---
- hosts: 127.0.0.1
  connection: local
  remote_user: malk
  sudo: yes
  roles:
    - dist-upgrade
    - apt-add-ppa
    - git
    - crypto
    - oracle-java-8
    - grive
    - fonts
    - window-management
